## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
dist: trusty
os:
  - linux
  - osx
julia:
  - 1.3
notifications:
  email: false

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg;
                     cd(Pkg.dir("AutoPages"));
                     Pkg.add("Coverage");
                     using Coverage;
                     Codecov.submit(Codecov.process_folder())'
